[package]
name = "mul_model"
version = "0.1.3"
authors = ["smallnest <smallnest@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.98",features = ["derive"]}
serde_json = "1.0.40" 
rmp-serde = "0.13.7"
rpcx =  { version = "0.1.3", path = "../../rpcx" }